import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[window]
decorations = "None"
blur = true
startup_mode = "Maximized"

[font]
size = 16
normal = { family = "JetBrainsMono Nerd Font" }
offset = { y = 3, x = 1 }

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new-session"]

# correct alacritty key-code, so that neovim mappings can work normally.
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"


[[keyboard.bindings]]
key = "A"
mods = "Command"
chars = "\u0002"
# action = "SendString"
# string = "\u{02}"  # Ctrl + b (0x02 in hexadecimal)
