import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[window]
decorations = "None"
blur = true
startup_mode = "Maximized"

[font]
size = 17
normal = { family = "JetBrainsMono Nerd Font" }
# normal = { family = "BlexMono Nerd Font" }
offset = { y = 3, x = 0 }

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "~/.config/alacritty/start-tmux.sh"]

# correct alacritty key-code, so that neovim mappings can work normally.
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control|Shift"

# [[keyboard.bindings]]
# chars = "\u0002"
# key = "A"
# mods = "Alt"
# string = "\u{02}"  # Ctrl + b (0x02 in hexadecimal)
